-- ==============================================================================
-- Migration: Supabase RBAC Pattern 1 (Custom Claims via Auth Hook)
-- Roles: 'user' (Default user) | 'researcher' (Researcher role)
-- ==============================================================================

-- 1. Tạo Enum cho các role ứng dụng
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'app_role') THEN
        CREATE TYPE public.app_role AS ENUM ('user', 'researcher');
    END IF;
END $$;

-- 2. Tạo bảng lưu trữ role của người dùng
CREATE TABLE IF NOT EXISTS public.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    role public.app_role NOT NULL DEFAULT 'user'::public.app_role,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT user_roles_user_id_unique UNIQUE (user_id)
);

-- Bật Row Level Security (RLS)
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Policies: Người dùng authenticated có thể đọc, tạo và cập nhật role của chính mình (hỗ trợ test demo)
DROP POLICY IF EXISTS "Users can view own role" ON public.user_roles;
CREATE POLICY "Users can view own role"
ON public.user_roles FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own role" ON public.user_roles;
CREATE POLICY "Users can update own role"
ON public.user_roles FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own role" ON public.user_roles;
CREATE POLICY "Users can insert own role"
ON public.user_roles FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- 3. Function & Trigger tự động tạo record trong public.user_roles khi user đăng ký
CREATE OR REPLACE FUNCTION public.handle_new_user_role()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  desired_role_text TEXT;
  assigned_role public.app_role;
BEGIN
  -- Lấy desired_role từ raw_user_meta_data nếu có
  desired_role_text := NEW.raw_user_meta_data->>'desired_role';
  
  IF desired_role_text = 'researcher' THEN
    assigned_role := 'researcher'::public.app_role;
  ELSE
    assigned_role := 'user'::public.app_role;
  END IF;

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, assigned_role)
  ON CONFLICT (user_id) DO UPDATE SET role = EXCLUDED.role;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created_add_role ON auth.users;
CREATE TRIGGER on_auth_user_created_add_role
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_role();

-- 4. Custom Access Token Hook để nhúng claim 'user_role' vào JWT
CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  claims JSONB;
  user_role public.app_role;
  meta_role TEXT;
BEGIN
  -- 1. Truy vấn role của user từ public.user_roles
  SELECT role INTO user_role
  FROM public.user_roles
  WHERE user_id = (event->>'user_id')::UUID;

  -- 2. Nếu chưa có trong bảng (lúc vừa đăng ký), fallback đọc từ user_metadata
  IF user_role IS NULL THEN
    meta_role := COALESCE(
      event->'claims'->'user_metadata'->>'desired_role',
      event->'user_metadata'->>'desired_role'
    );
    IF meta_role = 'researcher' THEN
      user_role := 'researcher'::public.app_role;
    ELSE
      user_role := 'user'::public.app_role;
    END IF;
  END IF;

  claims := event->'claims';

  -- Inject 'user_role' vào claims
  IF user_role IS NOT NULL THEN
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  ELSE
    claims := jsonb_set(claims, '{user_role}', '"user"');
  END IF;

  event := jsonb_set(event, '{claims}', claims);
  RETURN event;
END;
$$;

-- 5. RPC Function hỗ trợ đổi role nhanh cho demo & kiểm thử
CREATE OR REPLACE FUNCTION public.switch_user_role(new_role public.app_role)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  INSERT INTO public.user_roles (user_id, role, updated_at)
  VALUES (auth.uid(), new_role, now())
  ON CONFLICT (user_id) 
  DO UPDATE SET role = EXCLUDED.role, updated_at = now();

  -- Cập nhật cả metadata để token refresh đồng bộ ngay lập tức
  UPDATE auth.users
  SET raw_user_meta_data = jsonb_set(COALESCE(raw_user_meta_data, '{}'::jsonb), '{desired_role}', to_jsonb(new_role::text))
  WHERE id = auth.uid();
END;
$$;

-- 6. Cấp quyền thực thi và truy cập
GRANT USAGE ON SCHEMA public TO supabase_auth_admin, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.custom_access_token_hook TO supabase_auth_admin;
GRANT EXECUTE ON FUNCTION public.switch_user_role TO authenticated;
REVOKE EXECUTE ON FUNCTION public.custom_access_token_hook FROM authenticated, anon, public;

GRANT SELECT, INSERT, UPDATE ON TABLE public.user_roles TO authenticated;
GRANT SELECT ON TABLE public.user_roles TO supabase_auth_admin;
GRANT ALL ON TABLE public.user_roles TO postgres, service_role;

-- 7. Bảng dữ liệu mẫu (Research Papers) để minh họa RLS
CREATE TABLE IF NOT EXISTS public.research_papers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    abstract TEXT,
    content TEXT,
    is_published BOOLEAN DEFAULT true,
    author_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.research_papers ENABLE ROW LEVEL SECURITY;

-- Mọi user (cả role 'user' và 'researcher') đều có thể đọc bài báo đã xuất bản
DROP POLICY IF EXISTS "Anyone authenticated can view published papers" ON public.research_papers;
CREATE POLICY "Anyone authenticated can view published papers"
ON public.research_papers FOR SELECT
TO authenticated
USING (is_published = true OR auth.uid() = author_id);

-- CHỈ user có claim 'researcher' mới được thêm bài báo nghiên cứu
DROP POLICY IF EXISTS "Only researchers can insert papers" ON public.research_papers;
CREATE POLICY "Only researchers can insert papers"
ON public.research_papers FOR INSERT
TO authenticated
WITH CHECK (
    (auth.jwt() ->> 'user_role') = 'researcher'
);

-- Researcher có thể cập nhật bài báo do chính mình tạo
DROP POLICY IF EXISTS "Researchers can update their own papers" ON public.research_papers;
CREATE POLICY "Researchers can update their own papers"
ON public.research_papers FOR UPDATE
TO authenticated
USING (
    (auth.jwt() ->> 'user_role') = 'researcher' AND auth.uid() = author_id
);
